# spring.application.name=journelApp
# spring.data.mongodb.uri=mongodb+srv://Yug_07:yug123@cluster0.1g8xnng.mongodb.net/?appName=Cluster0
# spring.data.mongodb.database=journaldb
# spring.data.mongodb.auto-index-creation=true


spring:
  data:
    mongodb:
      uri: mongodb+srv://Yug_07:yug123@cluster0.1g8xnng.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
  servlet:
    context-path:
